version: '3.3'
services:
  db:
    image: postgres:11
    ports:
      - "54322:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: 'redis:5.0-alpine'
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - './tmp/redis:/var/lib/redis/data'

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis